services:
  # frontend container
  app:
    build:
      context: ./letour-app
    ports:
      - "3000:3000"
    volumes:
      - ./letour-app:/letour-app
    environment:
      - CHOKIDAR_USEPOLLING=true

  # backend container
  janus-ab:
    container_name: janus
    build:
      context: janus-ab
    #volumes:
      # expose configuration files
      #- ./janus-ab/config:/usr/local/etc/janus
    ports:
      - "7088:7088" # HTTPS admin API
      - "8088:8088" # HTTP API
      - "8188:8188" # WebSocket API
      #- "8888:8888" # Secure WebSocket API (not using)
      - "10000-10200:10000-10200/udp" # Media ports for WebRTC
    #environment:
      #- TURN_SERVER=turn:your-turn-server-url

  # janus demo container
  janus-ab-demo:
    container_name: janus-demo
    build:
      context: janus-ab-demo
    ports:
      - "8080:8080"
